/*
 * Harbour 3.2.0dev (r2502031126)
 * GNU C 7.5 (64-bit)
 * Generated C source from "hbfimage/hbfimage.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( FI_ADJUSTBRIGHTNESS );
HB_FUNC_EXTERN( FI_ADJUSTCONTRAST );
HB_FUNC_EXTERN( FI_ADJUSTGAMMA );
HB_FUNC_EXTERN( FI_ALLOCATE );
HB_FUNC_EXTERN( FI_ALLOCATET );
HB_FUNC_EXTERN( FI_APPENDPAGE );
HB_FUNC_EXTERN( FI_CLONE );
HB_FUNC_EXTERN( FI_CLOSEMULTIBITMAP );
HB_FUNC_EXTERN( FI_COLORQUANTIZE );
HB_FUNC_EXTERN( FI_CONVERTTO16BITS555 );
HB_FUNC_EXTERN( FI_CONVERTTO16BITS565 );
HB_FUNC_EXTERN( FI_CONVERTTO24BITS );
HB_FUNC_EXTERN( FI_CONVERTTO32BITS );
HB_FUNC_EXTERN( FI_CONVERTTO4BITS );
HB_FUNC_EXTERN( FI_CONVERTTO8BITS );
HB_FUNC_EXTERN( FI_CONVERTTOGREYSCALE );
HB_FUNC_EXTERN( FI_CONVERTTORGBF );
HB_FUNC_EXTERN( FI_CONVERTTOSTANDARDTYPE );
HB_FUNC_EXTERN( FI_CONVERTTOTYPE );
HB_FUNC_EXTERN( FI_COPY );
HB_FUNC_EXTERN( FI_CREATEICCPROFILE );
HB_FUNC_EXTERN( FI_DEINITIALISE );
HB_FUNC_EXTERN( FI_DELETEPAGE );
HB_FUNC_EXTERN( FI_DESTROYICCPROFILE );
HB_FUNC_EXTERN( FI_DITHER );
HB_FUNC_EXTERN( FI_FLIPHORIZONTAL );
HB_FUNC_EXTERN( FI_FLIPVERTICAL );
HB_FUNC_EXTERN( FI_GETBACKGROUNDCOLOR );
HB_FUNC_EXTERN( FI_GETBITS );
HB_FUNC_EXTERN( FI_GETBLUEMASK );
HB_FUNC_EXTERN( FI_GETBPP );
HB_FUNC_EXTERN( FI_GETCHANNEL );
HB_FUNC_EXTERN( FI_GETCOLORSUSED );
HB_FUNC_EXTERN( FI_GETCOLORTYPE );
HB_FUNC_EXTERN( FI_GETCOPYRIGHTMESSAGE );
HB_FUNC_EXTERN( FI_GETDIBSIZE );
HB_FUNC_EXTERN( FI_GETDOTSPERMETERX );
HB_FUNC_EXTERN( FI_GETDOTSPERMETERY );
HB_FUNC_EXTERN( FI_GETFILETYPE );
HB_FUNC_EXTERN( FI_GETFILETYPEFROMMEMORY );
HB_FUNC_EXTERN( FI_GETGREENMASK );
HB_FUNC_EXTERN( FI_GETHEIGHT );
HB_FUNC_EXTERN( FI_GETICCPROFILE );
HB_FUNC_EXTERN( FI_GETIMAGETYPE );
HB_FUNC_EXTERN( FI_GETINFO );
HB_FUNC_EXTERN( FI_GETINFOHEADER );
HB_FUNC_EXTERN( FI_GETLINE );
HB_FUNC_EXTERN( FI_GETPAGECOUNT );
HB_FUNC_EXTERN( FI_GETPALETTE );
HB_FUNC_EXTERN( FI_GETPITCH );
HB_FUNC_EXTERN( FI_GETREDMASK );
HB_FUNC_EXTERN( FI_GETSCANLINE );
HB_FUNC_EXTERN( FI_GETTRANSPARENCYCOUNT );
HB_FUNC_EXTERN( FI_GETTRANSPARENCYTABLE );
HB_FUNC_EXTERN( FI_GETVERSION );
HB_FUNC_EXTERN( FI_GETWIDTH );
HB_FUNC_EXTERN( FI_HASBACKGROUNDCOLOR );
HB_FUNC_EXTERN( FI_INITIALISE );
HB_FUNC_EXTERN( FI_INSERTPAGE );
HB_FUNC_EXTERN( FI_INVERT );
HB_FUNC_EXTERN( FI_ISLITTLEENDIAN );
HB_FUNC_EXTERN( FI_ISTRANSPARENT );
HB_FUNC_EXTERN( FI_LOAD );
HB_FUNC_EXTERN( FI_LOADFROMMEMORY );
HB_FUNC_EXTERN( FI_LOCKPAGE );
HB_FUNC_EXTERN( FI_MOVEPAGE );
HB_FUNC_EXTERN( FI_OPENMULTIBITMAP );
HB_FUNC_EXTERN( FI_PASTE );
HB_FUNC_EXTERN( FI_RESCALE );
HB_FUNC_EXTERN( FI_ROTATECLASSIC );
HB_FUNC_EXTERN( FI_ROTATEEX );
HB_FUNC_EXTERN( FI_SAVE );
HB_FUNC_EXTERN( FI_SETBACKGROUNDCOLOR );
HB_FUNC_EXTERN( FI_SETDOTSPERMETERX );
HB_FUNC_EXTERN( FI_SETDOTSPERMETERY );
HB_FUNC_EXTERN( FI_SETOUTPUTMESSAGE );
HB_FUNC_EXTERN( FI_SETTRANSPARENCYTABLE );
HB_FUNC_EXTERN( FI_SETTRANSPARENT );
HB_FUNC_EXTERN( FI_UNLOAD );
HB_FUNC_EXTERN( FI_UNLOCKPAGE );
HB_FUNC_EXTERN( FI_WINCONVFROMDIB );
HB_FUNC_EXTERN( FI_WINCONVTODIB );
HB_FUNC_EXTERN( FI_WINDRAW );
HB_FUNC( __HBEXTERN__HBFIMAGE__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBFIMAGE )
{ "FI_ADJUSTBRIGHTNESS", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_ADJUSTBRIGHTNESS )}, NULL },
{ "FI_ADJUSTCONTRAST", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_ADJUSTCONTRAST )}, NULL },
{ "FI_ADJUSTGAMMA", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_ADJUSTGAMMA )}, NULL },
{ "FI_ALLOCATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_ALLOCATE )}, NULL },
{ "FI_ALLOCATET", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_ALLOCATET )}, NULL },
{ "FI_APPENDPAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_APPENDPAGE )}, NULL },
{ "FI_CLONE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_CLONE )}, NULL },
{ "FI_CLOSEMULTIBITMAP", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_CLOSEMULTIBITMAP )}, NULL },
{ "FI_COLORQUANTIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_COLORQUANTIZE )}, NULL },
{ "FI_CONVERTTO16BITS555", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_CONVERTTO16BITS555 )}, NULL },
{ "FI_CONVERTTO16BITS565", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_CONVERTTO16BITS565 )}, NULL },
{ "FI_CONVERTTO24BITS", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_CONVERTTO24BITS )}, NULL },
{ "FI_CONVERTTO32BITS", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_CONVERTTO32BITS )}, NULL },
{ "FI_CONVERTTO4BITS", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_CONVERTTO4BITS )}, NULL },
{ "FI_CONVERTTO8BITS", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_CONVERTTO8BITS )}, NULL },
{ "FI_CONVERTTOGREYSCALE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_CONVERTTOGREYSCALE )}, NULL },
{ "FI_CONVERTTORGBF", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_CONVERTTORGBF )}, NULL },
{ "FI_CONVERTTOSTANDARDTYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_CONVERTTOSTANDARDTYPE )}, NULL },
{ "FI_CONVERTTOTYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_CONVERTTOTYPE )}, NULL },
{ "FI_COPY", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_COPY )}, NULL },
{ "FI_CREATEICCPROFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_CREATEICCPROFILE )}, NULL },
{ "FI_DEINITIALISE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_DEINITIALISE )}, NULL },
{ "FI_DELETEPAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_DELETEPAGE )}, NULL },
{ "FI_DESTROYICCPROFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_DESTROYICCPROFILE )}, NULL },
{ "FI_DITHER", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_DITHER )}, NULL },
{ "FI_FLIPHORIZONTAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_FLIPHORIZONTAL )}, NULL },
{ "FI_FLIPVERTICAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_FLIPVERTICAL )}, NULL },
{ "FI_GETBACKGROUNDCOLOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETBACKGROUNDCOLOR )}, NULL },
{ "FI_GETBITS", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETBITS )}, NULL },
{ "FI_GETBLUEMASK", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETBLUEMASK )}, NULL },
{ "FI_GETBPP", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETBPP )}, NULL },
{ "FI_GETCHANNEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETCHANNEL )}, NULL },
{ "FI_GETCOLORSUSED", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETCOLORSUSED )}, NULL },
{ "FI_GETCOLORTYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETCOLORTYPE )}, NULL },
{ "FI_GETCOPYRIGHTMESSAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETCOPYRIGHTMESSAGE )}, NULL },
{ "FI_GETDIBSIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETDIBSIZE )}, NULL },
{ "FI_GETDOTSPERMETERX", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETDOTSPERMETERX )}, NULL },
{ "FI_GETDOTSPERMETERY", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETDOTSPERMETERY )}, NULL },
{ "FI_GETFILETYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETFILETYPE )}, NULL },
{ "FI_GETFILETYPEFROMMEMORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETFILETYPEFROMMEMORY )}, NULL },
{ "FI_GETGREENMASK", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETGREENMASK )}, NULL },
{ "FI_GETHEIGHT", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETHEIGHT )}, NULL },
{ "FI_GETICCPROFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETICCPROFILE )}, NULL },
{ "FI_GETIMAGETYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETIMAGETYPE )}, NULL },
{ "FI_GETINFO", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETINFO )}, NULL },
{ "FI_GETINFOHEADER", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETINFOHEADER )}, NULL },
{ "FI_GETLINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETLINE )}, NULL },
{ "FI_GETPAGECOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETPAGECOUNT )}, NULL },
{ "FI_GETPALETTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETPALETTE )}, NULL },
{ "FI_GETPITCH", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETPITCH )}, NULL },
{ "FI_GETREDMASK", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETREDMASK )}, NULL },
{ "FI_GETSCANLINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETSCANLINE )}, NULL },
{ "FI_GETTRANSPARENCYCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETTRANSPARENCYCOUNT )}, NULL },
{ "FI_GETTRANSPARENCYTABLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETTRANSPARENCYTABLE )}, NULL },
{ "FI_GETVERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETVERSION )}, NULL },
{ "FI_GETWIDTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_GETWIDTH )}, NULL },
{ "FI_HASBACKGROUNDCOLOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_HASBACKGROUNDCOLOR )}, NULL },
{ "FI_INITIALISE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_INITIALISE )}, NULL },
{ "FI_INSERTPAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_INSERTPAGE )}, NULL },
{ "FI_INVERT", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_INVERT )}, NULL },
{ "FI_ISLITTLEENDIAN", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_ISLITTLEENDIAN )}, NULL },
{ "FI_ISTRANSPARENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_ISTRANSPARENT )}, NULL },
{ "FI_LOAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_LOAD )}, NULL },
{ "FI_LOADFROMMEMORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_LOADFROMMEMORY )}, NULL },
{ "FI_LOCKPAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_LOCKPAGE )}, NULL },
{ "FI_MOVEPAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_MOVEPAGE )}, NULL },
{ "FI_OPENMULTIBITMAP", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_OPENMULTIBITMAP )}, NULL },
{ "FI_PASTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_PASTE )}, NULL },
{ "FI_RESCALE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_RESCALE )}, NULL },
{ "FI_ROTATECLASSIC", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_ROTATECLASSIC )}, NULL },
{ "FI_ROTATEEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_ROTATEEX )}, NULL },
{ "FI_SAVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_SAVE )}, NULL },
{ "FI_SETBACKGROUNDCOLOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_SETBACKGROUNDCOLOR )}, NULL },
{ "FI_SETDOTSPERMETERX", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_SETDOTSPERMETERX )}, NULL },
{ "FI_SETDOTSPERMETERY", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_SETDOTSPERMETERY )}, NULL },
{ "FI_SETOUTPUTMESSAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_SETOUTPUTMESSAGE )}, NULL },
{ "FI_SETTRANSPARENCYTABLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_SETTRANSPARENCYTABLE )}, NULL },
{ "FI_SETTRANSPARENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_SETTRANSPARENT )}, NULL },
{ "FI_UNLOAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_UNLOAD )}, NULL },
{ "FI_UNLOCKPAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_UNLOCKPAGE )}, NULL },
{ "FI_WINCONVFROMDIB", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_WINCONVFROMDIB )}, NULL },
{ "FI_WINCONVTODIB", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_WINCONVTODIB )}, NULL },
{ "FI_WINDRAW", {HB_FS_PUBLIC}, {HB_FUNCNAME( FI_WINDRAW )}, NULL },
{ "__HBEXTERN__HBFIMAGE__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBFIMAGE__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBFIMAGE, "hbfimage/hbfimage.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBFIMAGE
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBFIMAGE )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBFIMAGE__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

