/*
 * Harbour 3.2.0dev (r2502031126)
 * GNU C 7.5 (64-bit)
 * Generated C source from "hbpgsql/hbpgsql.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( HB_PQCOPYFROMWA );
HB_FUNC_EXTERN( LO_EXPORT );
HB_FUNC_EXTERN( LO_IMPORT );
HB_FUNC_EXTERN( LO_UNLINK );
HB_FUNC_EXTERN( PG_ENCODING_TO_CHAR );
HB_FUNC_EXTERN( PQBACKENDPID );
HB_FUNC_EXTERN( PQBINARYTUPLES );
HB_FUNC_EXTERN( PQCANCEL );
HB_FUNC_EXTERN( PQCLIENTENCODING );
HB_FUNC_EXTERN( PQCMDSTATUS );
HB_FUNC_EXTERN( PQCMDTUPLES );
HB_FUNC_EXTERN( PQCONNECTDB );
HB_FUNC_EXTERN( PQCONNECTDBPARAMS );
HB_FUNC_EXTERN( PQCONNECTIONNEEDSPASSWORD );
HB_FUNC_EXTERN( PQCONNECTIONUSEDPASSWORD );
HB_FUNC_EXTERN( PQCONNECTPOLL );
HB_FUNC_EXTERN( PQCONNECTSTART );
HB_FUNC_EXTERN( PQCONNECTSTARTPARAMS );
HB_FUNC_EXTERN( PQCONSUMEINPUT );
HB_FUNC_EXTERN( PQDB );
HB_FUNC_EXTERN( PQERRORMESSAGE );
HB_FUNC_EXTERN( PQESCAPEBYTEA );
HB_FUNC_EXTERN( PQESCAPEBYTEACONN );
HB_FUNC_EXTERN( PQESCAPESTRING );
HB_FUNC_EXTERN( PQEXEC );
HB_FUNC_EXTERN( PQEXECPARAMS );
HB_FUNC_EXTERN( PQEXECPREPARED );
HB_FUNC_EXTERN( PQFCOUNT );
HB_FUNC_EXTERN( PQFLUSH );
HB_FUNC_EXTERN( PQFMOD );
HB_FUNC_EXTERN( PQFNAME );
HB_FUNC_EXTERN( PQFNUMBER );
HB_FUNC_EXTERN( PQFSIZE );
HB_FUNC_EXTERN( PQFTABLE );
HB_FUNC_EXTERN( PQFTYPE );
HB_FUNC_EXTERN( PQGETCANCEL );
HB_FUNC_EXTERN( PQGETISNULL );
HB_FUNC_EXTERN( PQGETLENGTH );
HB_FUNC_EXTERN( PQGETRESULT );
HB_FUNC_EXTERN( PQGETVALUE );
HB_FUNC_EXTERN( PQHOST );
HB_FUNC_EXTERN( PQISBUSY );
HB_FUNC_EXTERN( PQISNONBLOCKING );
HB_FUNC_EXTERN( PQISTHREADSAFE );
HB_FUNC_EXTERN( PQLASTREC );
HB_FUNC_EXTERN( PQLIBVERSION );
HB_FUNC_EXTERN( PQMETADATA );
HB_FUNC_EXTERN( PQNFIELDS );
HB_FUNC_EXTERN( PQNTUPLES );
HB_FUNC_EXTERN( PQOIDSTATUS );
HB_FUNC_EXTERN( PQOIDVALUE );
HB_FUNC_EXTERN( PQOPTIONS );
HB_FUNC_EXTERN( PQPARAMETERSTATUS );
HB_FUNC_EXTERN( PQPASS );
HB_FUNC_EXTERN( PQPING );
HB_FUNC_EXTERN( PQPINGPARAMS );
HB_FUNC_EXTERN( PQPORT );
HB_FUNC_EXTERN( PQPREPARE );
HB_FUNC_EXTERN( PQPROTOCOLVERSION );
HB_FUNC_EXTERN( PQPUTCOPYDATA );
HB_FUNC_EXTERN( PQPUTCOPYEND );
HB_FUNC_EXTERN( PQREQUESTCANCEL );
HB_FUNC_EXTERN( PQRESET );
HB_FUNC_EXTERN( PQRESETPOLL );
HB_FUNC_EXTERN( PQRESETSTART );
HB_FUNC_EXTERN( PQRESSTATUS );
HB_FUNC_EXTERN( PQRESULT2ARRAY );
HB_FUNC_EXTERN( PQRESULTERRORFIELD );
HB_FUNC_EXTERN( PQRESULTERRORMESSAGE );
HB_FUNC_EXTERN( PQRESULTSTATUS );
HB_FUNC_EXTERN( PQSENDQUERY );
HB_FUNC_EXTERN( PQSERVERVERSION );
HB_FUNC_EXTERN( PQSETCLIENTENCODING );
HB_FUNC_EXTERN( PQSETDBLOGIN );
HB_FUNC_EXTERN( PQSETERRORVERBOSITY );
HB_FUNC_EXTERN( PQSETNONBLOCKING );
HB_FUNC_EXTERN( PQSOCKET );
HB_FUNC_EXTERN( PQSSLATTRIBUTE );
HB_FUNC_EXTERN( PQSSLINUSE );
HB_FUNC_EXTERN( PQSTATUS );
HB_FUNC_EXTERN( PQTRACE );
HB_FUNC_EXTERN( PQTRACECREATE );
HB_FUNC_EXTERN( PQTRANSACTIONSTATUS );
HB_FUNC_EXTERN( PQTTY );
HB_FUNC_EXTERN( PQUNESCAPEBYTEA );
HB_FUNC_EXTERN( PQUNTRACE );
HB_FUNC_EXTERN( PQUSER );
HB_FUNC_EXTERN( TPQQUERY );
HB_FUNC_EXTERN( TPQROW );
HB_FUNC_EXTERN( TPQSERVER );
HB_FUNC( __HBEXTERN__HBPGSQL__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBPGSQL )
{ "HB_PQCOPYFROMWA", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_PQCOPYFROMWA )}, NULL },
{ "LO_EXPORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( LO_EXPORT )}, NULL },
{ "LO_IMPORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( LO_IMPORT )}, NULL },
{ "LO_UNLINK", {HB_FS_PUBLIC}, {HB_FUNCNAME( LO_UNLINK )}, NULL },
{ "PG_ENCODING_TO_CHAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( PG_ENCODING_TO_CHAR )}, NULL },
{ "PQBACKENDPID", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQBACKENDPID )}, NULL },
{ "PQBINARYTUPLES", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQBINARYTUPLES )}, NULL },
{ "PQCANCEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQCANCEL )}, NULL },
{ "PQCLIENTENCODING", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQCLIENTENCODING )}, NULL },
{ "PQCMDSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQCMDSTATUS )}, NULL },
{ "PQCMDTUPLES", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQCMDTUPLES )}, NULL },
{ "PQCONNECTDB", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQCONNECTDB )}, NULL },
{ "PQCONNECTDBPARAMS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQCONNECTDBPARAMS )}, NULL },
{ "PQCONNECTIONNEEDSPASSWORD", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQCONNECTIONNEEDSPASSWORD )}, NULL },
{ "PQCONNECTIONUSEDPASSWORD", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQCONNECTIONUSEDPASSWORD )}, NULL },
{ "PQCONNECTPOLL", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQCONNECTPOLL )}, NULL },
{ "PQCONNECTSTART", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQCONNECTSTART )}, NULL },
{ "PQCONNECTSTARTPARAMS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQCONNECTSTARTPARAMS )}, NULL },
{ "PQCONSUMEINPUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQCONSUMEINPUT )}, NULL },
{ "PQDB", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQDB )}, NULL },
{ "PQERRORMESSAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQERRORMESSAGE )}, NULL },
{ "PQESCAPEBYTEA", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQESCAPEBYTEA )}, NULL },
{ "PQESCAPEBYTEACONN", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQESCAPEBYTEACONN )}, NULL },
{ "PQESCAPESTRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQESCAPESTRING )}, NULL },
{ "PQEXEC", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQEXEC )}, NULL },
{ "PQEXECPARAMS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQEXECPARAMS )}, NULL },
{ "PQEXECPREPARED", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQEXECPREPARED )}, NULL },
{ "PQFCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQFCOUNT )}, NULL },
{ "PQFLUSH", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQFLUSH )}, NULL },
{ "PQFMOD", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQFMOD )}, NULL },
{ "PQFNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQFNAME )}, NULL },
{ "PQFNUMBER", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQFNUMBER )}, NULL },
{ "PQFSIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQFSIZE )}, NULL },
{ "PQFTABLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQFTABLE )}, NULL },
{ "PQFTYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQFTYPE )}, NULL },
{ "PQGETCANCEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQGETCANCEL )}, NULL },
{ "PQGETISNULL", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQGETISNULL )}, NULL },
{ "PQGETLENGTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQGETLENGTH )}, NULL },
{ "PQGETRESULT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQGETRESULT )}, NULL },
{ "PQGETVALUE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQGETVALUE )}, NULL },
{ "PQHOST", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQHOST )}, NULL },
{ "PQISBUSY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQISBUSY )}, NULL },
{ "PQISNONBLOCKING", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQISNONBLOCKING )}, NULL },
{ "PQISTHREADSAFE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQISTHREADSAFE )}, NULL },
{ "PQLASTREC", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQLASTREC )}, NULL },
{ "PQLIBVERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQLIBVERSION )}, NULL },
{ "PQMETADATA", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQMETADATA )}, NULL },
{ "PQNFIELDS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQNFIELDS )}, NULL },
{ "PQNTUPLES", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQNTUPLES )}, NULL },
{ "PQOIDSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQOIDSTATUS )}, NULL },
{ "PQOIDVALUE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQOIDVALUE )}, NULL },
{ "PQOPTIONS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQOPTIONS )}, NULL },
{ "PQPARAMETERSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQPARAMETERSTATUS )}, NULL },
{ "PQPASS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQPASS )}, NULL },
{ "PQPING", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQPING )}, NULL },
{ "PQPINGPARAMS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQPINGPARAMS )}, NULL },
{ "PQPORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQPORT )}, NULL },
{ "PQPREPARE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQPREPARE )}, NULL },
{ "PQPROTOCOLVERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQPROTOCOLVERSION )}, NULL },
{ "PQPUTCOPYDATA", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQPUTCOPYDATA )}, NULL },
{ "PQPUTCOPYEND", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQPUTCOPYEND )}, NULL },
{ "PQREQUESTCANCEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQREQUESTCANCEL )}, NULL },
{ "PQRESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQRESET )}, NULL },
{ "PQRESETPOLL", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQRESETPOLL )}, NULL },
{ "PQRESETSTART", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQRESETSTART )}, NULL },
{ "PQRESSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQRESSTATUS )}, NULL },
{ "PQRESULT2ARRAY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQRESULT2ARRAY )}, NULL },
{ "PQRESULTERRORFIELD", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQRESULTERRORFIELD )}, NULL },
{ "PQRESULTERRORMESSAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQRESULTERRORMESSAGE )}, NULL },
{ "PQRESULTSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQRESULTSTATUS )}, NULL },
{ "PQSENDQUERY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQSENDQUERY )}, NULL },
{ "PQSERVERVERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQSERVERVERSION )}, NULL },
{ "PQSETCLIENTENCODING", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQSETCLIENTENCODING )}, NULL },
{ "PQSETDBLOGIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQSETDBLOGIN )}, NULL },
{ "PQSETERRORVERBOSITY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQSETERRORVERBOSITY )}, NULL },
{ "PQSETNONBLOCKING", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQSETNONBLOCKING )}, NULL },
{ "PQSOCKET", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQSOCKET )}, NULL },
{ "PQSSLATTRIBUTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQSSLATTRIBUTE )}, NULL },
{ "PQSSLINUSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQSSLINUSE )}, NULL },
{ "PQSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQSTATUS )}, NULL },
{ "PQTRACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQTRACE )}, NULL },
{ "PQTRACECREATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQTRACECREATE )}, NULL },
{ "PQTRANSACTIONSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQTRANSACTIONSTATUS )}, NULL },
{ "PQTTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQTTY )}, NULL },
{ "PQUNESCAPEBYTEA", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQUNESCAPEBYTEA )}, NULL },
{ "PQUNTRACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQUNTRACE )}, NULL },
{ "PQUSER", {HB_FS_PUBLIC}, {HB_FUNCNAME( PQUSER )}, NULL },
{ "TPQQUERY", {HB_FS_PUBLIC}, {HB_FUNCNAME( TPQQUERY )}, NULL },
{ "TPQROW", {HB_FS_PUBLIC}, {HB_FUNCNAME( TPQROW )}, NULL },
{ "TPQSERVER", {HB_FS_PUBLIC}, {HB_FUNCNAME( TPQSERVER )}, NULL },
{ "__HBEXTERN__HBPGSQL__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBPGSQL__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBPGSQL, "hbpgsql/hbpgsql.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBPGSQL
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBPGSQL )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBPGSQL__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

