/*
 * Harbour 3.2.0dev (r2502031126)
 * GNU C 7.5 (64-bit)
 * Generated C source from "hbmagic/hbmagic.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( HB_MAGIC_SIMPLE );
HB_FUNC_EXTERN( MAGIC_BUFFER );
HB_FUNC_EXTERN( MAGIC_CHECK );
HB_FUNC_EXTERN( MAGIC_COMPILE );
HB_FUNC_EXTERN( MAGIC_ERRNO );
HB_FUNC_EXTERN( MAGIC_ERROR );
HB_FUNC_EXTERN( MAGIC_FILE );
HB_FUNC_EXTERN( MAGIC_LOAD );
HB_FUNC_EXTERN( MAGIC_OPEN );
HB_FUNC_EXTERN( MAGIC_SETFLAGS );
HB_FUNC( __HBEXTERN__HBMAGIC__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBMAGIC )
{ "HB_MAGIC_SIMPLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_MAGIC_SIMPLE )}, NULL },
{ "MAGIC_BUFFER", {HB_FS_PUBLIC}, {HB_FUNCNAME( MAGIC_BUFFER )}, NULL },
{ "MAGIC_CHECK", {HB_FS_PUBLIC}, {HB_FUNCNAME( MAGIC_CHECK )}, NULL },
{ "MAGIC_COMPILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( MAGIC_COMPILE )}, NULL },
{ "MAGIC_ERRNO", {HB_FS_PUBLIC}, {HB_FUNCNAME( MAGIC_ERRNO )}, NULL },
{ "MAGIC_ERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( MAGIC_ERROR )}, NULL },
{ "MAGIC_FILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( MAGIC_FILE )}, NULL },
{ "MAGIC_LOAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( MAGIC_LOAD )}, NULL },
{ "MAGIC_OPEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( MAGIC_OPEN )}, NULL },
{ "MAGIC_SETFLAGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( MAGIC_SETFLAGS )}, NULL },
{ "__HBEXTERN__HBMAGIC__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBMAGIC__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBMAGIC, "hbmagic/hbmagic.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBMAGIC
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBMAGIC )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBMAGIC__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

